from typing import Union, List

class ccPythonInstance:
    def haveSelection(self) -> bool: ...

    def haveOneSelection(self) -> bool: ...

    def getSelectedEntites(self) -> List[Union[ccHObject, ccPointCloud, ccMesh]]: ...


def GetInstance() -> ccPythonInstance: ...
