FROM ubuntu:23.10


RUN apt update
RUN apt install -qy cmake ninja-build build-essential xvfb doxygen git \
    libqt5svg5-dev libqt5opengl5-dev qtbase5-dev qttools5-dev qttools5-dev-tools \
    pybind11-dev
RUN apt install -qy python3-sphinx python3-breathe


RUN git clone --recursive https://github.com/CloudCompare/CloudCompare
COPY . /CloudCompare/plugins/private/CloudCompare-PythonPlugin

RUN mkdir /CloudCompare/cmake-build-debug
RUN cmake -S /CloudCompare \
          -B CloudCompare/cmake-build-debug \
          -GNinja  \
          -DCMAKE_BUILD_TYPE=Debug \
          -DPLUGIN_PYTHON=ON


RUN cmake --build /CloudCompare/cmake-build-debug
RUN cmake --install /CloudCompare/cmake-build-debug
