param(
    [Parameter(Mandatory = $true)]
    [String]$CloudCompareInstallFolder,
    [Parameter(Mandatory = $true)]
    [String]$PythonDllSuffix
)


&heat `
    dir "$CloudCompareInstallFolder\plugins\Python" `
    -scom `
    -frag `
    -srd `
    -sreg `
    -gg `
    -cg PythonEnvironment `
    -dr PythonEnvironmentDir `
    -o PythonEnvironment.wxs 

&heat `
    dir "$CloudCompareInstallFolder\resources" `
    -scom `
    -frag `
    -srd `
    -sreg `
    -gg `
    -cg QtResources `
    -dr QtResourcesDir `
    -o QtResources.wxs 

&candle `
    -arch x64 `
    -dSourceInstallPath="$CloudCompareInstallFolder" `
    -dPythonSuffix="$PythonDllSuffix" `
    .\Installer.wxs `
    .\PythonEnvironment.wxs `
    .\QtResources.wxs


&light `
    -ext WixUIExtension `
    .\Installer.wixobj `
    .\PythonEnvironment.wixobj `
    .\QtResources.wixobj `
    -b "$CloudCompareInstallFolder\plugins\Python" `
    -b "$CloudCompareInstallFolder\resources" `
    -o CloudCompare-PythonPlugin-Setup.msi


# The heat command is taken from https://stackoverflow.com/questions/26550763/wix-how-to-copy-a-directory-to-install-folder
# Basically:
# it 'harvest' the "$CloudCompareInstallFolder\plugins\Python" directory
#   -scom -sfrag -srd -sreg = Suppress COM elements, fragments, root directory as element, registry harvesting (these options will create a grouping that most applications can use)
#   -gg = generate GUID's now (this will put the GUID's into your output file, rather than using a wildcard "*". The advantage here is you can use non-standard TARGETDIR, which would not qualify for autogenerated GUID's)
#   -cg PythonEnvironment : The ID we reference in the <Fearure> of the Installer.wxs
#    -dr PythonEnvironmentDir : ID of the directory (in Installer.wxs) were harvest files will be installed